### PR TITLE
Added BasicComponent

### PR DESCRIPTION
**Pull request by Tamy123**

### CODE REVIEW

**Comment by Tamy123** [comment]
Please resolve the conflicts and merge the pull request :)

**Comment by Swap76** [comment]
@Tamy123 Great Work :-)

**Comment by Tamy123** [comment]
Thanks again :)

**Comment by Swap76** [comment]
@Tamy123  It was great working with you.

Looking forward to working with you :-)

Star to the repo is highly appreciated.

**Comment by Swap76** [comment]
@Tamy123 The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Pull request merged**
